BASE_DIRECTORY = "/mnt/gokstad"
NON_PRIVILEGED_USERNAME = "gokstad"
TIMEZONE = "Europe/Madrid"
PAPER_SIZE = "A4"
toolchain_xml_filename = "toolchain_data.xml"
system_xml_filename = "system_data.xml"
configuration_xml_filename = "configuration_data.xml"
