BASE_DIRECTORY = "/mnt/gokstad"
NON_PRIVILEGED_USERNAME = "gokstad"
TIMEZONE = "Europe/Madrid"
PAPER_SIZE = "A4"
ROOT_PARTITION_NAME = ""
ROOT_PARTITION_NUMBER = ""
FILESYSTEM_PARTITION_TYPE = "ext4"
SWAP_PARTITION_NAME = ""
ETH0_IP_ADDRESS = "192.168.99.2"
ETH0_GATEWAY_ADDRESS = "192.168.99.1"
ETH0_BROADCAST_ADDRESS = "192.168.99.255"
DOMAIN_NAME = "localdomain"
# OpenNIC DNS servers
DNS_ADDRESS_1 = "52.174.55.168"
DNS_ADDRESS_2 = "31.3.135.232"
HOSTNAME = "lfs"
LANG = "en_US.UTF-8"
DISTRIBUTION_NAME = "Linux From Scratch"
DISTRIBUTION_VERSION = "8.0 LFSBuilder"
DISTRIBUTION_DESCRIPTION = "Linux From Scratch 8.0 from LFSBuilder"

toolchain_xml_filename = "toolchain_data.xml"
system_xml_filename = "system_data.xml"
configuration_xml_filename = "configuration_data.xml"
